# Generated by Django 2.2.4 on 2020-08-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
